MSG_SUCESS='Success'
MSG_FAILED='FAILED'
MSG_EXCELSU='Excel Upload Sucessfully.'
MSG_EXCELF='Excel format not correct.'
MSG_REQ='Please Insert Required Field.'
MSG_UNF='user not found.'
MSG_DDS='data deleted successfully.'
MSG_UPDATE='Data Updated Successfully.'
MSG_DETAILSUPDATE='Your details have been updated successfully.'
MSG_ADDED='Data Added Successfully'
MSG_RTOAR='This resource is related to other active record.'
MSG_NOC='NO CONTENT'
MSG_UN='UNAUTHORIZED'
MSG_NF='Not Found'

