# Generated by Django 2.1 on 2021-07-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_remove_vendor_service_list_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_service_list',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
