# Generated by Django 2.1 on 2021-07-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('superadmin', '0001_initial'),
        ('master', '0010_vendor_service_list_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_Address',
            new_name='Employee_Address_Vendor',
        ),
    ]
