# Generated by Django 2.1 on 2021-07-19 13:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('master', '0011_auto_20210713_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine_Autho_Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='system', max_length=100, null=True)),
                ('modified_by', models.CharField(default='system', max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('country_id', models.CharField(blank=True, max_length=10, null=True)),
                ('authorization_type', models.BooleanField(default=False)),
                ('access_type', models.CharField(blank=True, max_length=10, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id')),
            ],
            options={
                'verbose_name': 'Vaccine Autho Country',
                'verbose_name_plural': 'Vaccine Autho Country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vaccine_Master',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='system', max_length=100, null=True)),
                ('modified_by', models.CharField(default='system', max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('vaccine_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vaccine_company_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Vaccine Master',
                'verbose_name_plural': 'Vaccine Master',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='vaccine_autho_country',
            name='vaccine_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Vaccine_Master'),
        ),
    ]
