# Generated by Django 2.1 on 2021-07-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_code',
            field=models.CharField(default='emp001', max_length=100, unique=True),
        ),
    ]
