# Generated by Django 2.1 on 2021-07-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_emp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
