# Generated by Django 2.1 on 2021-07-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210713_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
