# Generated by Django 2.1 on 2021-07-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210713_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emp_code',
        ),
    ]
