# Generated by Django 2.1 on 2021-07-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_emp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
