# Generated by Django 2.1 on 2021-07-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
