# Generated by Django 2.2 on 2021-06-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20210621_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_category',
            name='category_id',
            field=models.IntegerField(blank=True, max_length=200),
        ),
    ]
