# Generated by Django 2.2 on 2021-06-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20210622_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor_master',
            name='vendor_id',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visa_purpose',
            name='VPID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='vendor_master',
            unique_together={('vendor_type', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='visa_purpose',
            unique_together={('VPID', 'organization')},
        ),
    ]
