# Generated by Django 2.2 on 2021-06-29 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('master', '0007_auto_20210629_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Income',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='system', max_length=100, null=True)),
                ('modified_by', models.CharField(default='system', max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('income_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(choices=[('Tax Payer', 'Tax Payer'), ('Spouse', 'Spouse'), ('Joint', 'Joint')], max_length=100)),
                ('attachment', models.CharField(blank=True, max_length=300, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Vendor')),
            ],
            options={
                'verbose_name': 'income_type',
                'verbose_name_plural': 'income_type',
                'managed': True,
            },
        ),
    ]
