# Generated by Django 2.2 on 2021-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_vendor_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_income',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Tax Payer', 'Tax Payer'), ('Spouse', 'Spouse'), ('Joint', 'Joint')], max_length=100, null=True),
        ),
    ]
