# Generated by Django 2.1.15 on 2021-03-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_policy',
            name='column11',
        ),
        migrations.RemoveField(
            model_name='country_policy',
            name='column12',
        ),
    ]
