# Generated by Django 2.1 on 2021-05-10 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('master', '0002_auto_20210325_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_policy',
            name='home_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country_policy',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
        migrations.AddField(
            model_name='country_policy',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='per_diem',
            name='band',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='per_diem',
            name='home_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
