# Generated by Django 2.1 on 2021-07-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210712_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital_gains_income',
            name='test',
        ),
    ]
