# Generated by Django 2.2 on 2021-06-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('master', '0002_auto_20210616_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('pid', 'organization')},
        ),
    ]
