# Generated by Django 2.1 on 2021-07-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_capital_gains_income_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital_gains_income',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='capital_gains_income',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='capital_gains_income',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='capital_gains_income',
            name='travel_req',
        ),
        migrations.RemoveField(
            model_name='capital_gains_income',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Capital_Gains_Income',
        ),
    ]
