# Generated by Django 2.1 on 2021-07-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_vendor_income_column13'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_income',
            name='column14',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
