# Generated by Django 2.1 on 2021-07-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_vendor_income_column14'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_income',
            name='column13',
        ),
        migrations.RemoveField(
            model_name='vendor_income',
            name='column14',
        ),
    ]
