# Generated by Django 2.2 on 2021-06-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('master', '0005_auto_20210621_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pid_disp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('pid_disp', 'organization')},
        ),
    ]
