# Generated by Django 2.1 on 2021-07-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_remove_vendor_service_list_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_income',
            old_name='account_type',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='vendor_income',
            name='tax_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
