# Generated by Django 2.1 on 2021-07-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20210713_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_service_list',
            name='testaa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
