# Generated by Django 2.1 on 2021-07-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20210717_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_autho_country',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
    ]
