# Generated by Django 2.1 on 2021-07-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20210719_1042'),
        ('master', '0012_auto_20210719_1339'),
    ]

    operations = [
    ]
