# Generated by Django 2.1 on 2021-07-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_auto_20210717_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_autho_country',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
