# Generated by Django 2.1 on 2021-07-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_vendor_authorized_service_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_authorized_service_list',
            name='emp_code',
        ),
        migrations.RemoveField(
            model_name='vendor_authorized_service_list',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vendor_authorized_service_list',
            name='travel_req',
        ),
        migrations.RemoveField(
            model_name='vendor_authorized_service_list',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Vendor_Authorized_Service_List',
        ),
    ]
