# Generated by Django 2.1 on 2021-07-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_vendor_authorized_service_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital_gains_income',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='capital_gains_income',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='capital_gains_income',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='capital_gains_income',
            name='travel_req',
        ),
        migrations.RemoveField(
            model_name='capital_gains_income',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendor_authorized_service_list',
            name='emp_code',
        ),
        migrations.RemoveField(
            model_name='vendor_authorized_service_list',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vendor_authorized_service_list',
            name='travel_req',
        ),
        migrations.RemoveField(
            model_name='vendor_authorized_service_list',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendor_income',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='vendor_income',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vendor_income',
            name='travel_req',
        ),
        migrations.RemoveField(
            model_name='vendor_income',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendor_service_list',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='vendor_service_list',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vendor_service_list',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendor_service_list',
            name='vendor_status',
        ),
        migrations.RemoveField(
            model_name='vendor_status',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='vendor_status',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vendor_status',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Capital_Gains_Income',
        ),
        migrations.DeleteModel(
            name='Vendor_Authorized_Service_List',
        ),
        migrations.DeleteModel(
            name='Vendor_Income',
        ),
        migrations.DeleteModel(
            name='vendor_Service_List',
        ),
        migrations.DeleteModel(
            name='Vendor_Status',
        ),
    ]
