# Generated by Django 2.1.15 on 2021-03-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa_request_document_draft',
            name='column10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visa_request_document_draft',
            name='column11',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
