# Generated by Django 2.2 on 2021-06-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visa_request',
            old_name='column3',
            new_name='column13',
        ),
        migrations.AlterField(
            model_name='visa_request',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='master.Project', to_field='pid'),
        ),
    ]
