# Generated by Django 2.1.15 on 2021-03-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_auto_20210325_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa_request_document_draft',
            name='column10',
        ),
        migrations.RemoveField(
            model_name='visa_request_document_draft',
            name='column11',
        ),
        migrations.RemoveField(
            model_name='visa_request_document_draft',
            name='column9',
        ),
    ]
