# Generated by Django 2.1.15 on 2021-03-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault_type_info',
            name='doc_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
