# Generated by Django 2.1 on 2021-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault_type_info',
            name='test',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
