# Generated by Django 2.1 on 2021-05-06 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20210422_1252'),
        ('vault', '0002_remove_vault_type_info_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='system', max_length=100, null=True)),
                ('modified_by', models.CharField(default='system', max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('compl_ques', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Compliance',
                'verbose_name_plural': 'Compliance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee_compliance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='system', max_length=100, null=True)),
                ('modified_by', models.CharField(default='system', max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('compl_ques', models.CharField(blank=True, max_length=200, null=True)),
                ('compl_ans', models.BooleanField(default=False)),
                ('emp_code', models.ForeignKey(default='emp001', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', to_field='emp_code')),
            ],
            options={
                'verbose_name': 'Employee Compliance',
                'verbose_name_plural': 'Employee Compliance',
                'managed': True,
            },
        ),
    ]
