# Generated by Django 2.1 on 2021-06-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_vault_type_info_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault_type_info',
            name='test',
        ),
    ]
