# Generated by Django 2.1 on 2021-06-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_compliance_compl_ques_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliance',
            old_name='compl_ques_id',
            new_name='ques_id',
        ),
        migrations.RenameField(
            model_name='employee_compliance',
            old_name='compl_ques_id',
            new_name='ques_id',
        ),
    ]
