# Generated by Django 2.1 on 2021-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_auto_20210603_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='test',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
