# Generated by Django 2.1 on 2021-06-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_compliance_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliance',
            old_name='ques_id_compl',
            new_name='ques_id',
        ),
        migrations.RenameField(
            model_name='employee_compliance',
            old_name='ques_id_compl',
            new_name='ques_id',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='test',
        ),
    ]
