# Generated by Django 2.1.15 on 2021-03-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_request',
            name='pri_type_req',
        ),
    ]
