# Generated by Django 2.1.15 on 2021-02-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visa', '0001_initial'),
        ('employee', '__first__'),
        ('master', '0001_initial'),
        ('superadmin', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa_request_action_history',
            name='visa_req_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visa.Visa_Request', to_field='visa_req_id'),
        ),
        migrations.AddField(
            model_name='travel_request_draft',
            name='emp_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', to_field='emp_code'),
        ),
        migrations.AddField(
            model_name='travel_request_draft',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
        migrations.AddField(
            model_name='travel_request_draft',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Travel_Request_Draft', to='master.Project', to_field='pid'),
        ),
        migrations.AddField(
            model_name='travel_request_details_draft',
            name='assignment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_request_details_draft', to='master.Assignment_Type'),
        ),
        migrations.AddField(
            model_name='travel_request_details_draft',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
        migrations.AddField(
            model_name='travel_request_details_draft',
            name='travel_req_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_request_details', to='travel.Travel_Request_Draft', to_field='travel_req_id'),
        ),
        migrations.AddField(
            model_name='travel_request_details',
            name='assignment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_request_details', to='master.Assignment_Type'),
        ),
        migrations.AddField(
            model_name='travel_request_details',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
        migrations.AddField(
            model_name='travel_request_details',
            name='travel_req_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_request_details', to='travel.Travel_Request', to_field='travel_req_id'),
        ),
        migrations.AddField(
            model_name='travel_request_dependent_draft',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
        migrations.AddField(
            model_name='travel_request_dependent_draft',
            name='travel_req_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel_Request_Draft', to_field='travel_req_id'),
        ),
        migrations.AddField(
            model_name='travel_request_dependent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
        migrations.AddField(
            model_name='travel_request_dependent',
            name='travel_req_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel_Request', to_field='travel_req_id'),
        ),
        migrations.AddField(
            model_name='travel_request_action_history',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', to_field='emp_code'),
        ),
        migrations.AddField(
            model_name='travel_request_action_history',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
        migrations.AddField(
            model_name='travel_request_action_history',
            name='travel_req_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel_Request', to_field='travel_req_id'),
        ),
        migrations.AddField(
            model_name='travel_request',
            name='emp_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', to_field='emp_code'),
        ),
        migrations.AddField(
            model_name='travel_request',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
        migrations.AddField(
            model_name='travel_request',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_request', to='master.Project', to_field='pid'),
        ),
        migrations.AddField(
            model_name='assignment_travel_tax_grid',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
        migrations.AddField(
            model_name='assignment_travel_tax_grid',
            name='travel_req_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel_Request', to_field='travel_req_id'),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='travel_req_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel_Request', to_field='travel_req_id'),
        ),
    ]
