# Generated by Django 2.2 on 2021-06-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_request',
            name='column1',
        ),
        migrations.AddField(
            model_name='travel_request',
            name='attachments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
