# Generated by Django 2.1 on 2021-07-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='travel_req_status_vendor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
