# Generated by Django 2.1 on 2021-07-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_assignment_travel_request_status_travel_req_status_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_travel_tax_grid',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
