# Generated by Django 2.1.15 on 2021-03-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20210325_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='column10',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='column11',
        ),
    ]
