# Generated by Django 2.1.15 on 2021-03-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_travel_request_pri_type_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_request',
            name='column13',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel_request',
            name='pri_type_req',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
