# Generated by Django 2.1.15 on 2021-03-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20210322_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_request',
            name='column13',
        ),
    ]
