# Generated by Django 2.1 on 2021-07-13 14:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('employee', '0001_initial'),
        ('travel', '0004_remove_assignment_travel_tax_grid_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_Vendor_Immigration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='system', max_length=100, null=True)),
                ('modified_by', models.CharField(default='system', max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('Host_job_code', models.CharField(blank=True, max_length=100, null=True)),
                ('Host_job_description', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', to_field='emp_code')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id')),
                ('travel_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel_Request', to_field='travel_req_id')),
            ],
            options={
                'verbose_name': 'Travel Vendor Immigration',
                'managed': True,
            },
        ),
    ]
