# Generated by Django 2.1 on 2021-07-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_travel_vendor_immigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='move_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
