# Generated by Django 2.1 on 2021-07-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20210715_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment_travel_request_status',
            old_name='delivery_date',
            new_name='tent_delivery_date',
        ),
        migrations.RenameField(
            model_name='assignment_travel_request_status',
            old_name='move_date',
            new_name='tent_move_date',
        ),
    ]
