# Generated by Django 2.1 on 2021-07-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_auto_20210721_1723'),
        ('travel', '0008_auto_20210715_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='capital_gains_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='dividend_income_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='employment_income_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='host_job_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='host_text_box',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='house_hold_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='house_hold_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='income_from_partnership_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='interest_income_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='rent_and_royalty_income_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='retirement_income_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='self_employment_income_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_attestatios_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_attestatios_estimated_visa_approvel_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_attestatios_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attestatios', to='master.vendor_Service_List_status'),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_business_visa_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_business_visa_estimated_visa_approvel_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_business_visa_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_visa', to='master.vendor_Service_List_status'),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_consular_services_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_consular_services_estimated_visa_approvel_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_consular_services_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consular_services', to='master.vendor_Service_List_status'),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_document_translation_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_document_translation_estimated_visa_approvel_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_document_translation_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_translation', to='master.vendor_Service_List_status'),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_permanent_residence_appli_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_permanent_residence_appli_esti_visa_aprovl_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_permanent_residence_appli_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_residence_appli', to='master.vendor_Service_List_status'),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_residence_permit_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_residence_permit_estimated_visa_approvel_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_residence_permit_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence_permit', to='master.vendor_Service_List_status'),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_visa_extension_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_visa_extension_estimated_visa_approvel_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_visa_extension_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visa_extension', to='master.vendor_Service_List_status'),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_work_visa_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_work_visa_estimated_visa_approvel_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignment_travel_request_status',
            name='services_work_visa_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.vendor_Service_List_status'),
        ),
    ]
