# Generated by Django 2.1 on 2021-07-22 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('master', '0019_auto_20210721_1723'),
        ('employee', '0006_remove_employee_vaccine_name'),
        ('travel', '0010_income_tax_vendor_authorized_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immigration_Vendor_Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='system', max_length=100, null=True)),
                ('modified_by', models.CharField(default='system', max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('services_list', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_visa_approve_date', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations')),
                ('status_audit_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.vendor_Service_List_status')),
                ('travel_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel_Request')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_attestatios_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_attestatios_estimated_visa_approvel_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_attestatios_status',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_business_visa_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_business_visa_estimated_visa_approvel_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_business_visa_status',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_consular_services_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_consular_services_estimated_visa_approvel_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_consular_services_status',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_document_translation_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_document_translation_estimated_visa_approvel_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_document_translation_status',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_permanent_residence_appli_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_permanent_residence_appli_esti_visa_aprovl_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_permanent_residence_appli_status',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_residence_permit_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_residence_permit_estimated_visa_approvel_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_residence_permit_status',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_visa_extension_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_visa_extension_estimated_visa_approvel_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_visa_extension_status',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_work_visa_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_work_visa_estimated_visa_approvel_date',
        ),
        migrations.RemoveField(
            model_name='assignment_travel_request_status',
            name='services_work_visa_status',
        ),
    ]
