# Generated by Django 2.1 on 2021-07-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20210722_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigration_vendor_service',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', to_field='emp_code'),
        ),
        migrations.AlterField(
            model_name='immigration_vendor_service',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Organizations', to_field='org_id'),
        ),
        migrations.AlterField(
            model_name='immigration_vendor_service',
            name='travel_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Travel_Request', to_field='travel_req_id'),
        ),
        migrations.AlterField(
            model_name='immigration_vendor_service',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Vendor', to_field='vendor_id'),
        ),
    ]
