# Generated by Django 2.1.15 on 2021-03-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_chat',
            name='column1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_chat',
            name='column2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
