# Generated by Django 2.1.15 on 2021-02-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender_events',
            name='is_deleted',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calender_events',
            name='status',
            field=models.CharField(default='True', max_length=50, null=True),
        ),
    ]
