# Generated by Django 2.1.15 on 2021-02-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210226_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender_events',
            name='is_visible',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calender_events',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
