# Generated by Django 2.1 on 2021-07-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210719_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
