# Generated by Django 2.1.15 on 2021-03-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210325_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_Chat',
            new_name='Chat_Message',
        ),
        migrations.AlterModelOptions(
            name='chat_message',
            options={'managed': True, 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Message'},
        ),
    ]
