# Generated by Django 2.1.15 on 2021-03-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210325_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat_Message',
            new_name='EMPMessage',
        ),
        migrations.AlterModelOptions(
            name='empmessage',
            options={},
        ),
    ]
