# Generated by Django 2.1.15 on 2021-02-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210226_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender_events',
            name='is_deleted',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='calender_events',
            name='is_visible',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
