# Generated by Django 2.1 on 2021-07-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_vaccine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='vaccine_name',
        ),
    ]
