# Generated by Django 2.1.15 on 2021-03-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210325_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMPMessage',
        ),
    ]
