# Generated by Django 2.1 on 2021-07-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210719_1144'),
        ('employee', '0004_remove_employee_vaccine_name'),
    ]

    operations = [
    ]
