# Generated by Django 2.1 on 2021-07-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_merge_20210719_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='vaccine_name',
        ),
    ]
