# Generated by Django 2.1.15 on 2021-03-25 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_delete_empmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_emp_code', models.CharField(max_length=200, null=True)),
                ('receiver_emp_code', models.CharField(max_length=200, null=True)),
                ('chat_message', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('column1', models.CharField(blank=True, max_length=100, null=True)),
                ('column2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
