# Generated by Django 2.1.15 on 2021-03-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_calender_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_visa_denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_denied_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_org_info',
            name='current_working_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_org_info',
            name='current_working_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_org_info',
            name='home_country_band',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_org_info',
            name='host_country_band',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_visa_detail',
            name='visa_entry_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
