# Generated by Django 2.1.15 on 2021-03-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='column2',
        ),
    ]
