# Generated by Django 2.1.15 on 2021-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_message_column2'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='column2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
