# Generated by Django 2.1.15 on 2021-03-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20210325_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='column1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='column26',
        ),
    ]
