# Generated by Django 2.1.15 on 2021-03-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20210325_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='column1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
