# Generated by Django 2.1.15 on 2021-03-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_message_column1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Message_Chat',
        ),
    ]
