# Generated by Django 2.1.15 on 2021-03-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20210326_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_chat',
            name='column1',
        ),
        migrations.AddField(
            model_name='message_chat',
            name='treading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
