# Generated by Django 2.1.15 on 2021-03-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20210326_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_chat',
            old_name='treading',
            new_name='thread',
        ),
    ]
