# Generated by Django 2.1.15 on 2021-04-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20210326_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_chat',
            name='ticket_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
