# Generated by Django 2.1.15 on 2021-04-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_message_chat_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.CharField(blank=True, default='demo_supervisor_1', max_length=100),
        ),
    ]
