# Generated by Django 2.1.15 on 2021-04-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20210406_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_chat',
            name='chat_message',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
